package ui;

import javax.swing.*;
import java.awt.*;

public class WaitingDialog extends JDialog {
    private JPanel contentPane;
    private JLabel waitingText;

    public WaitingDialog() {
        setContentPane(contentPane);
        setModal(true);

        Font font = new Font("Arial", Font.BOLD, 22);
        waitingText.setFont(font);
        waitingText.setText("Waiting player to join...");
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            WaitingDialog dialog = new WaitingDialog();
            dialog.setTitle("Gomoku Game");
            dialog.setSize(300, 200);
            dialog.setLocationRelativeTo(null); // make center
            dialog.setVisible(true);
            System.exit(0);
        });

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        contentPane.add(panel1, BorderLayout.CENTER);
        waitingText = new JLabel();
        waitingText.setHorizontalAlignment(0);
        waitingText.setText("Waiting player to join...");
        panel1.add(waitingText, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
